### PR TITLE
Add S3 Endpoint Support

### PR DESCRIPTION
**Pull request by camjac251**
This will offer support for other storage platforms that offer S3 like APIs such as
Backblaze B2, Wasabi, and DigitalOcean Spaces

### CODE REVIEW

**Comment by camjac251** [comment]
installer.js currently has `#storage_endpoint` required when it can be optional.

**Comment by SergiX44** [comment]
If can be optional just remove the `.prop('required', 'required')` from https://github.com/SergiX44/XBackBone/pull/216/commits/4dced7dd2045970daa1f7bfa48339949358f1782#diff-2448901093d91384ce23e82b65082097R47
and handle the default as empty string.

**Comment by camjac251** [comment]
Is this right?

**Comment by SergiX44** [comment]
The `data-default-local=null` doesn't mean anything, the null value should be handled in https://github.com/SergiX44/XBackBone/pull/216/commits/4dced7dd2045970daa1f7bfa48339949358f1782#diff-0630d924071d2a47b5221c4a9888c4b8R57

If the returned value is empty and the endpoint is the default one should be not set or set to null according to the s3client docs.

**Pull request merged**
