### PR TITLE
Screencloud support

### PR DESCRIPTION
**Pull request by SergiX44**

### CODE REVIEW

**Comment by gerroon** [comment]
Hi,

Thanks for implementing it. I get  500 when I try to see if the url works, and in screencloud loading "install from url" never fully loads and it stops at %25 progress

`https://DOMAIN.com/imgshare/user/token_xxxxxxxxxxxxxxxxxx/config/screencloud`

Please bear in mind that XBackbone works perfectly with sharing, uplaoding thumbnails and it works perfectly with Sharex. I was trying to see if I could use Screencloud as a client on Linux.

I use it under Apache with  Sqlite.  I am using  v3.3.3 


```

500 Internal Server Error

Unexpected error while handling the request.

```

**Comment by SergiX44** [comment]
That was an issue one of the 3.x releases, download the latest release zip from github, and extract the folder in `resources/uploaders` in correct directory

**Comment by SergiX44** [comment]
The folder in `/resources` should match this: https://github.com/SergiX44/XBackBone/tree/master/resources

**Comment by gerroon** [comment]
Thanks, that seemed to fix the initial issue but now I get this error in Screencloud when done with taking a screenshot

```
Upload failed!
Could not upload to: https://DOMAIN.com/imgshare
Error: the JSON object must be str, not 'bytes'

```

**Comment by SergiX44** [comment]
> Thanks, that seemed to fix the initial issue but now I get this error in Screencloud when done with taking a screenshot
> 
> ```
> Upload failed!
> Could not upload to: https://DOMAIN.com/imgshare
> Error: the JSON object must be str, not 'bytes'
> ```

Seems an error with python, on which platform do you use Screencloud?

**Comment by gerroon** [comment]
I use Screencloud on Linux Debian Testing X64

**Comment by SergiX44** [comment]
> I use Screencloud on Linux Debian Testing X64

Can you try to replace the line here:
https://github.com/SergiX44/XBackBone/blob/master/resources/uploaders/screencloud/main.py#L82

With
`response = json.loads(res.read().decode('utf-8'))`
I think is because the newer python version, if works I'll patch it in the next release

**Comment by gerroon** [comment]
Hi

I did that but the result is the same. Do I need to add the plugin in SC again?  There does not seem to be a way to delete it upload it again.

**Comment by SergiX44** [comment]
> Hi
> 
> I did that but the result is the same. Do I need to add the plugin in SC again? There does not seem to be a way to delete it upload it again.
> 
> ```
>         try:
>             res = urllib.request.urlopen(r)
>             #response = json.loads(res.read())
>             response = json.loads(res.read().decode('utf-8'))
>             url = response.get('url')
>     
>             if not url:
>                 raise Exception(response.get('message'))
> 
>             ScreenCloud.setUrl(url)
> ```

Yes you need to re-download it on top of it, and than restart sc

**Comment by gerroon** [comment]
Thanks for the pointers. That seems to work and solve the issue.

**Pull request merged**
